### ISSUE TITLE
Add pages

### ISSUE THREAD

**Issue by suaJeong-777** [suaJeong-777/Comento_project#1]
##Description

>Information Architecture에 나타난 모든 페이지들을 추가하여 이동할 수 있도록 한다

##Todo
- [ ] 메인 페이지 생성
- [ ] 메인페이지에 나타나는 직무부트캠프, 실무 PT, VOD, 커뮤니티, 로그인 페이지 추가
- [ ] 아이콘(메뉴, 알림) 생성하고 메뉴 하위에 회사 소개 추가
